### ISSUE TITLE
[TEST] iSEE package demo for EuroBioC2023

### ISSUE THREAD

**Issue by bioc-workshop-dev** [Bioconductor/workshop-contributions#61]
/request id="test" title="iSEE package demo for EuroBioC2023" description="This package provides the material for the iSEE package demo at EuroBioC2023" section="TEST" startfile="README.md" source="iSEE/iSEEDemoEuroBioC2023" docker="ghcr.io/isee/iseedemoeurobioc2023:latest"

**Comment by almahmoud** [comment]
/request id="test" title="iSEE package demo for EuroBioC2023" description="This package provides the material for the iSEE package demo at EuroBioC2023" section="TEST" startfile="README.md" source="iSEE/iSEEDemoEuroBioC2023" docker="ghcr.io/isee/iseedemoeurobioc2023:latest"

**Comment by bioc-workshop-dev** [comment]
/request id="test" title="iSEE package demo for EuroBioC2023" description="This package provides the material for the iSEE package demo at EuroBioC2023" section="TEST" startfile="README.md" source="iSEE/iSEEDemoEuroBioC2023" docker="ghcr.io/isee/iseedemoeurobioc2023:latest"

**Comment by bioc-workshop-dev** [comment]
/request id="test" title="iSEE package demo for EuroBioC2023" description="This package provides the material for the iSEE package demo at EuroBioC2023" section="TEST" startfile="README.md" source="iSEE/iSEEDemoEuroBioC2023" docker="ghcr.io/isee/iseedemoeurobioc2023:latest"

**Comment by bioc-workshop-dev** [comment]
/request id="test" title="iSEE package demo for EuroBioC2023" description="This package provides the material for the iSEE package demo at EuroBioC2023" section="TEST" startfile="README.md" source="iSEE/iSEEDemoEuroBioC2023" docker="ghcr.io/isee/iseedemoeurobioc2023:latest"

**Comment by almahmoud** [comment]
/request id="test" title="iSEE package demo for EuroBioC2023" description="This package provides the material for the iSEE package demo at EuroBioC2023" section="TEST" startfile="README.md" source="iSEE/iSEEDemoEuroBioC2023" docker="ghcr.io/isee/iseedemoeurobioc2023:latest"

**Comment by bioc-workshop-dev** [comment]
/request id="test" title="iSEE package demo for EuroBioC2023" description="This package provides the material for the iSEE package demo at EuroBioC2023" section="TEST" startfile="README.md" source="iSEE/iSEEDemoEuroBioC2023" docker="ghcr.io/isee/iseedemoeurobioc2023:latest"

**Comment by almahmoud** [comment]
_AUTO-GENERATED RESPONSE_
Your request has been received and has passed initial screening. :sparkles:

Below are the detected values:

```
source='test'
title='iSEE package demo for EuroBioC2023'
description='This package provides the material for the iSEE package demo at EuroBioC2023'
section='TEST'
source='iSEE/iSEEDemoEuroBioC2023'
docker='ghcr.io/isee/iseedemoeurobioc2023:latest'
port='8787'
command='echo "setwd(\"/home/rstudio\"); setHook(\"rstudio.sessionInit\", function(newSession) { if (newSession) rstudioapi::filesPaneNavigate(getwd()) }, action = \"append\")" > /home/rstudio/.Rprofile; /init'
pkglist=''
vignettes=''
```

If these are as expected, no further action is needed at this time. Please wait for an admin's response.
If any changes are needed, please re-run the /request action with desired values.
