### ISSUE TITLE
[biocAsia2023] test

### ISSUE THREAD

**Issue by bioc-workshop-dev** [Bioconductor/workshop-contributions#67]
**DO NOT INCLUDE REQUESTS IN THE FIRST COMMENT.**
**PLEASE POST THIS TEMPLATE UNCHANGED THEN FOLLOW ITS INSTRUCTIONS IN A NEW
COMMENT**

# General Notes
This repository serves as a mostly automated pipeline for deploying workshops
to the [Bioconductor Workshop](https://workshop.bioconductor.org).

# Bot Commands

Issues in this repository are monitored to by a bot. All commands need to be
written on the first line of the comment, in a single line.

## Example Docker Request

```
/request
  id='tidybioc2023'
  title='Tidy Transcriptomics'
  description='For Single-Cell RNA Sequencing Analyses'
  section='Smorgasbord 2023'
  source='https://github.com/tidytranscriptomics-workshops/bioc2023_tidytranscriptomics'
  docker='ghcr.io/tidytranscriptomics-workshops/bioc2023_tidytranscriptomics:latest'
```

Note. The example `/request` is on multiple lines for readability.

**Comment by bioc-workshop-dev** [comment]
/request id="test" title="test" description="" section="biocAsia2023" startfile="README.md" source="https://github.com/" docker=":" pkglist="test,me,you" vignettes=""

**Comment by almahmoud** [comment]
_AUTO-GENERATED RESPONSE_
Your request has been received but is currently failing initial screening.
Please retry your request ensuring all parameters are passed in correctly.
