### ISSUE TITLE
[BBCC2023] Orchestrating Large-Scale Single-Cell Analysis with Bioconductor

### ISSUE THREAD

**Issue by LiNk-NY** [Bioconductor/workshop-contributions#73]
**DO NOT INCLUDE REQUESTS IN THE FIRST COMMENT.**
**PLEASE POST THIS TEMPLATE UNCHANGED THEN FOLLOW ITS INSTRUCTIONS IN A NEW
COMMENT**

# General Notes
This repository serves as a mostly automated pipeline for deploying workshops
to the [Bioconductor Workshop](https://workshop.bioconductor.org).

# Bot Commands

Issues in this repository are monitored to by a bot. All commands need to be
written on the first line of the comment, in a single line.

## Example Docker Request

```
/request
  id='tidybioc2023'
  title='Tidy Transcriptomics'
  description='For Single-Cell RNA Sequencing Analyses'
  section='Smorgasbord 2023'
  source='https://github.com/tidytranscriptomics-workshops/bioc2023_tidytranscriptomics'
  docker='ghcr.io/tidytranscriptomics-workshops/bioc2023_tidytranscriptomics:latest'
```

Note. The example `/request` is on multiple lines for readability.

## Additional Workshop Information

Expected Number of Participants: 30

Workshop Date(s): December 07, 2023 - December 07, 2023

Workshop Start Time (approx.): 08:30

**Comment by LiNk-NY** [comment]
/request id="BBCC.OSCA" title="Orchestrating Large-Scale Single-Cell Analysis with Bioconductor" description="This tutorial aims to provide a solid foundation in using Bioconductor tools for single-cell RNA-seq analysis by walking through various steps of typical workflows using example datasets" section="BBCC2023" startfile="README.md" source="drighelli/BBCC.OSCA" docker="ghcr.io/drighelli/bbcc.osca:b3b7133"

**Comment by almahmoud** [comment]
_AUTO-GENERATED RESPONSE_
Your request has been received and has passed initial screening. :sparkles:

Below are the detected values:

```
id='BBCC.OSCA'
title='Orchestrating Large-Scale Single-Cell Analysis with Bioconductor'
description='This tutorial aims to provide a solid foundation in using Bioconductor tools for single-cell RNA-seq analysis by walking through various steps of typical workflows using example datasets'
section='BBCC2023'
source='drighelli/BBCC.OSCA'
docker='ghcr.io/drighelli/bbcc.osca:b3b7133'
port='8787'
command='echo "setwd(\"/home/rstudio\"); setHook(\"rstudio.sessionInit\", function(newSession) { if (newSession) rstudioapi::filesPaneNavigate(getwd()) }, action = \"append\")" > /home/rstudio/.Rprofile; /init'
pkglist=''
vignettes=''
```

If these are as expected, no further action is needed at this time. Please wait for an admin's response.
If any changes are needed, please re-run the /request action with desired values.
